# Generated by Django 3.1.2 on 2020-10-10 22:27

import dj_gmap.fields
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GMapDirectionCache',
            fields=[
                ('id', models.CharField(max_length=402, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data', dj_gmap.fields.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
        ),
        migrations.CreateModel(
            name='GMapPointCache',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=9)),
                ('data', dj_gmap.fields.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
        ),
    ]
