# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_gmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmapdirectioncache',
            name='id',
            field=models.CharField(max_length=402, primary_key=True, serialize=False),
        ),
    ]
