# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-12 12:54
from __future__ import unicode_literals

import dj_gmap.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_gmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmapdirectioncache',
            name='data',
            field=dj_gmap.fields.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='gmappointcache',
            name='data',
            field=dj_gmap.fields.JSONField(default=[]),
        ),
    ]
